isard-webapp:
    restart: always
    build: .
    links:
        - "rethinkdb-container"
    hostname: isard-webapp
    expose:
        - "5000"
    command: python3 /isard/run_webapp.py

rethinkdb-container:
    image: rethinkdb
    hostname: rethinkdb

nginx:
    image: marvambass/nginx-ssl-secure
    ports:
        - "443:443"
    volumes:
        - "./install/docker/nginx/:/etc/nginx/external"
    hostname: nginx
    links:
        - "isard-webapp:isard-webapp"
