version: "3.5"
services:
  isard-hypervisor:
    container_name: isard-hypervisor
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "5900-5950:5900-5950"
    networks:
      - isard_network
    image: isard/hypervisor:${TAG:-latest}
    build:
      context: .
      dockerfile: hyper/docker/Dockerfile 
    privileged: true   
    restart: "no"

networks:
  isard_network:
    external: false
    name: isard_network
