apiVersion: apps/v1
kind: Deployment
metadata:
  name: hyper
spec:
  selector:
    matchLabels:
      app: hyper
  template:
    metadata:
      labels:
        app: hyper
    spec:
      containers:
        - name: hyper
          image: isard/hyper:2.0.0
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 1312

---
apiVersion: v1
kind: Service
metadata:
  name: hyper
spec:
  selector:
    app: hyper
  ports:
    - port: 1312
