apiVersion: v2
name: isard-orchestrator
description: A Helm chart for the Orchestrator Isard microservice. You probably don't want to install this but 'isard'
type: application
version: 0.1.0
appVersion: 2.0.0
