apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "orchestrator.fullname" . }}
  labels:
    {{- include "orchestrator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "orchestrator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "orchestrator.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.imageRegistry }}/orchestrator:{{ .Chart.AppVersion }}"
          env:
            - name: ORCHESTRATOR_REDIS_HOST
              value: "{{ .Release.Name}}-redis-cluster"
            - name: ORCHESTRATOR_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name }}-redis-cluster"
                  key: redis-password
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: {{ .Values.port }}
