apiVersion: v1
kind: Service
metadata:
  name: {{ template "orchestrator.fullname" . }}
  labels:
    {{- include "orchestrator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serviceType }}
  ports:
    - port: {{ .Values.port }}
  selector:
    {{- include "orchestrator.selectorLabels" . | nindent 4 }}
