site_name: IsardVDI
site_url: http://www.isardvdi.com
site_description: IsardVDI Open Source Virtual Desktops.
site_author: IsardVDI

repo_url: https://github.com/isard-vdi/isard

pages:
- Introduction: index.md
- Installation:
    - On linux: install/linux.md
    - Usind docker-compose: install/docker-compose.md
- Quick Start: quick-start/first.md
- About: about/license

copyright: Copyright &copy; 2016 <a href="http://www.isardvdi.com">IsardVDI</a>.
